name: eddl
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - cmake>=3.9.2
  - eigen==3.3.7
  - protobuf==3.11.4
  - libprotobuf==3.11.4  # We need to avoid problems with paths (idk why)
  - zlib
  - cudatoolkit-dev==10.1.243  #- cudatoolkit==10.2.89
  - cudnn      #==7.6.5
  - gtest
  - graphviz  # Build & Run
  - wget
  - doxygen  # Docs
  - python
  - pip
  - pip:
    - sphinx==3.2.1
    - sphinx_rtd_theme==0.5.0
    - sphinx-tabs==1.3.0
    - breathe==4.22.1
