{% set name = "eddl-cpu" %}  # If this is a package for GPU, use: "eddl-gpu"
{% set version = "0.8.3a" %}
{% set sha256 = "3d0678b4e00b9a5fb9c3905cf5bd3f5daa596684af47d1e77fbabbfd82f4e064" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake>=3.9.2
    - eigen==3.3.7
    - protobuf==3.11.4
    - libprotobuf==3.11.4  # We need to avoid problems with paths (idk why)
    - cudatoolkit
    - graphviz  # Build & Run
    - wget
  run:
    - cmake>=3.9.2
    - eigen==3.3.7
    - protobuf==3.11.4
    - libprotobuf==3.11.4  # We need to avoid problems with paths (idk why)
    - cudatoolkit
    - graphviz  # Build & Run
    - wget

test:
  commands:
    - test -d ${PREFIX}/include/eddl  # [unix]
    - test -f ${PREFIX}/include/eddl/apis/eddl.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/eddl/EDDLConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/libeddl${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'EDDL is an optimized tensor library for distributed deep learning with hardware transparency support for CPUs, GPUs and FPGAs'
  doc_url: https://deephealthproject.github.io/eddl/
  dev_url: https://github.com/deephealthproject/eddl/
